monolog:
    handlers:
        main:
            type: buffer
            handler: streamed
            channels: [app]
            level: debug
            bubble: false
        default:
            type: buffer
            handler: streamed
            channels: ["!app"]
            level: error
            bubble: false
        streamed:
            type:   stream
            path:   "php://stderr"
            include_stacktraces: true
